version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    networks:
      - backend 
    volumes:
      - social-postgres-data:/var/lib/postgresql/data
    ports:
      - "5500:5432"
  
volumes:
  social-postgres-data:

networks:
  backend:
    driver: bridge